<p><?php echo $block->getMain()->getId() ?></p>

<p><?php echo $block->getMain()->getInjectable()->getId() ?></p>

<p><?php echo $block->getMain()->getNonInjectable()->getId() ?></p>

<p><?php echo $block->getMain()->getAbstractUtil()->getName() ?></p>

<p><?php echo $block->getMain()->getHeavy()->getName() ?></p>

<p><?php echo $block->getMain()->getDefaultName()->getName() ?></p>

<p><?php echo $block->getMain()->getOptional()->getName() ?></p>
