<?php

/** @var $block \Magento\Catalog\Block\Product\View */

?>
<?php $_product = $block->getProduct(); ?>
<?php 


$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$StockState = $objectManager->get('\Magento\InventorySalesAdminUi\Model\GetSalableQuantityDataBySku');
$qty = $StockState->execute($block->getProduct()->getSku());

$salableQuantity = $qty[0]['qty'];

$buttonTitle = __('Add to Cart'); 


?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= $block->escapeHtml(__('Qty')) ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $block->getProductDefaultQty() * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <div class="actions">
            <?php if($salableQuantity==0): ?>

                <a href="/contact"
                        title="<?= $block->escapeHtmlAttr("Call for Availability") ?>"
                        class="primary tocart action "
                        id="">
                    <span><?= $block->escapeHtml("Call for Availability") ?></span>
            </a>
                <?php
                    else:
                ?>
                <button type="submit"
                title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                class="action primary tocart"
                id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?php endif;  ?>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>