<form action="<?php echo $block->getPost() ?>" method="post">

    <label for="fname">First Name:</label>
    <input type="text" name="first" id="fname" pattern="^[a-zA-Z]+$" required />

    <label for="lname">Last Name:</label>
    <input type="text" name="last" id="lname" pattern="^[a-zA-Z]+$" required />

    <label for="email">Email:</label>
    <input type="email" name="email" id="email" required />

    <label for="address">Address:</label>
    <input type="text" name="address" id="address" required />

    <label for="phone">Phone Number:</label>
    <input type="tel" name="phone" id="phone" pattern="[0-9]{10}" required />

    <button type="submit">Submit</button>
</form>