<?php
    $collection = $block->getCollection();
    // dump($collection);
?>

<table>
    <thead>
        <tr>
            <th>Id</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
        </tr>
    </thead>

    <?php foreach( $collection as $item ) : ?>
        <tbody>
            <tr>
                <td><?php echo $item->getId(); ?></td>
                <td><?php echo $item->getFirst(); ?></td>
                <td><?php echo $item->getLast(); ?></td>
                <td><?php echo $item->getEmail(); ?></td>
            </tr>
        </tbody>
    <?php endforeach; ?>
</table>